package com.mrivanplays.skins.api;

import com.google.common.base.Preconditions;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/** Represents the main object of the skins api. */
public interface SkinsApi {

  /**
   * Gets the player's server set skin. This could also return {@link #getOriginalSkinResponse(Player)} due
   * to how the plugin handles storing skins. The skin will be always updated if can.
   *
   * @param player the player you want to get the set skin of
   * @return response
   */
  @NotNull
  MojangResponse getSetSkinResponse(@NotNull Player player);

  /**
   * Gets the player's skin, which is set on the premium account of this player.
   *
   * @param player the player you want to get the original skin of
   * @return response
   * @see #getSkin(String)
   */
  @NotNull
  default MojangResponse getOriginalSkinResponse(@NotNull Player player) {
    Preconditions.checkNotNull(player, "player");
    return getSkin(player.getName());
  }

  /**
   * Returns whenever the set skin of the specified {@link Player} equals his original skin.
   *
   * @param player the player you want to check's skin
   * @return <code>true</code> if equal, <code>false</code> otherwise
   */
  default boolean isSetSkinOriginal(@NotNull Player player) {
    MojangResponse setSkin = getSetSkinResponse(player);
    MojangResponse originalSkin = getOriginalSkinResponse(player);
    return setSkin.equals(originalSkin);
  }

  /**
   * Gets the skin of the specified username by fetching {@link java.util.UUID} and skin from the
   * {@link DataProvider} set. The response is never null, however, the parts into the response may
   * be null if the data provider wasn't able to fetch them, for one reason or another. It is
   * recommended to run this asynchronously.
   *
   * @param username the username of the premium account you want to get skin
   * @return response with all data, or response with none data if data provider wasn't able to
   *     fetch it
   */
  @NotNull
  MojangResponse getSkin(@NotNull String username);

  /**
   * Sets the skin of the specified player.
   *
   * @param player the player you want to set the skin of
   * @param skin the skin in response form that you want to set on the player
   * @return whether or not the skin change was successful
   */
  boolean setSkin(@NotNull Player player, @NotNull MojangResponse skin);

  /**
   * Creates a new {@link SkullItemBuilder}
   *
   * @return skull item builder
   * @see SkullItemBuilder
   */
  @NotNull
  SkullItemBuilder newSkullItemBuilder();

  /**
   * Sets a new data provider, for fetching skin and uuid information.
   *
   * @param dataProvider data provider
   */
  void setDataProvider(@NotNull DataProvider dataProvider);

  /**
   * Returns the plugin's version info.
   *
   * @return detailed information object about the version of the plugin, implementing this api.
   */
  @NotNull
  SkinsVersionInfo getVersionInfo();

  /**
   * Returns the skull owner of the item, if the item is a skull item and was generated by the {@link SkullItemBuilder}.
   *
   * @param item item you want to get the skull owner of
   * @return response
   */
  @Nullable
  MojangResponse getSkullOwner(@NotNull ItemStack item);
}
